name: .NET Core

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
      - name: Restore packages
        run: msbuild ChensMinionRetarget.sln -t:restore
      - name: Restore packages
        run: msbuild ChensMinionRetarget.sln -t:restore
      - name: Run tests
        run: vstest.console.exe .\ChensMinionRetarget.Tests\Build\ChensMinionRetarget.Tests.dll
